<?xml version="1.0"?>
<!DOCTYPE class [
<!ELEMENT class (student)>
<!ELEMENT student (name,mobno,eid)>
<!ATTLIST student id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT mobno (#PCDATA)>
<!ELEMENT eid (#PCDATA)>
]>
<class>
	<student id="1288">
		<name>Akshay</name>
                <mobno>8978937353</mobno>
		<eid>1288@gvpce.ac.in</eid>
	</student>
	<student id="1201">
		<name>Ramu</name>
		<mobno>89183821657</mobno>
		<eid>1201@gvpce.ac.in</eid>
	</student>
	<student id="1202">
		<name>Babu</name>
		<mobno>9318292901</mobno>
		<eid>1202@gvpce.ac.in</eid>
	</student>
</class>